
# Start by giving a name to your workflow
name: Analyze branch

# then define on which event, here a push
on:
  push:
    # and the target with some regex to match our specific  branch names
    branches:
      - master

# We can now build our job
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Use an existing action, you can look in the market place to find what you need and how to use it, to setup the sonar scanner
      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v1

      # Another existing action, this one to checkout the repositoryss
      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      - if: endsWith(github.REF, '/master') == true
        name: 'Run an analysis of the master branch'
        run: sonar-scanner
          -Dsonar.host.url=https://sonar.pirobase.de/
          -Dsonar.login=5ba45215d8aedddd06f5fe7f0b3797b300227959
          -Dsonar.projectKey=API-Demo-gradle
          -Dsonar.scm.provider=git
          -Dsonar.java.binaries=/tmp